const itemData = [
  //BEVERAGES
  {
    item_name: "Blue Heaven",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "Italian Smooch",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "MASALA MINT COOLER",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "MANGO SMOOTHIE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "BLUEBERRY SMOOTHIE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "WATERMELON COOLER",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "VIRGIN PINA COLADA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "FRUIT PUNCH",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "GUAVA MERRY",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "APPLE MARTINI",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "WATERMELON GRANITIA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "APPLE VIRGIN MOJITO",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "BERRY FOREST",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "HAWAIIAN SUNRISE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "ORANGE PIROSHKA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "MINT MOJITO",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "FRESH LIME SODA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "STRAWBERRY MARGARETA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "BLUE HEAVEN",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "CHOICE OF SHAKE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "KIT KAT SHAKE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "CHOCOLATE OREO SHAKE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "CHESSE BROWNIE SHAKE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "STRAWBERRY MILK SHAKE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "CINDERELLA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "MISHRAMBU",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "SUNSET MOCKTAIL",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "CHOICE OF JUICE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "COLD COFFEE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "COLD COFFEE WITH ICE CREAM",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "LASSI",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "MASALA CHACH",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "REGULAR TEA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "MASALA TEA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "LEMON TEA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "ICED HIBISCUS MINT TEA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "HIBISCUS TEA",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "COFFEE LATTE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "HOT CHOCOLATE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "AMERICANO",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "CAPPUCCINO",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "HAZAL NUT",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "CARAMEL LATTE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "HOT MILK",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 8,
  },
  {
    item_name: "BOTTLE WATER",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 2,
  },
  {
    item_name: "SOFT DRINK",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 2,
  },
  {
    item_name: "DIET COKE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 2,
  },
  {
    item_name: "ZERO COKE",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 2,
  },
  {
    item_name: "ICE BUCKET",
    category: "Beverages",
    qty: 1,
    nc: false,
    ttp: 2,
  },

  //Hi Tea Snacks

  {
    item_name: "CORN & SPINACH CHEESE BALLS",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CIGAR ROLLS",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER PAKODA",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MIX PAKODA",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "GARLIC BREAD",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHEESE CHILLI TOAST",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FRENCH FRIES/SALTED/PERI PERI",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FRENCH FRIES SALTED PERI PERI",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FRENCH FRIES PERI PERI",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN FINGERS",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FISH FINGER",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PAV BHAJI",
    category: "Hi Tea",
    qty: 1,
    nc: false,
    ttp: 15,
  },

  //BAR BITE

  {
    item_name: "PEANUT MASALA",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PAPAD MASALA",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "ROASTED PAPAD",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PAPAD FRY",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PERI PERI FRIES",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FRENCH FRIES",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FRESH PANEER",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BOILED EGG",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "EGG BHURJI",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },

  {
    item_name: "MASALA OMLETTE",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SALTED PEANUTS",
    category: "Bar Bite",
    qty: 1,
    nc: false,
    ttp: 15,
  },

  //STEAM MOMOS
  {
    item_name: "Veg Momos",
    category: "Steam Momos",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PERI PERI MOMOS",
    category: "Steam Momos",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUSHROOM MOMOS",
    category: "Steam Momos",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN MOMOS",
    category: "Steam Momos",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PERI PERI CHICKEN MOMOS",
    category: "Steam Momos",
    qty: 1,
    nc: false,
    ttp: 15,
  },

  //TANDOORI MOMOS

  {
    item_name: "TANDOORI VEG MOMOS",
    category: "Steam Momos",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI CREAMY MOMOS",
    category: "Steam Momos",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI PAHADI MOMOS",
    category: "Steam Momos",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI CHICKEN MOMOS",
    category: "Steam Momos",
    qty: 1,
    nc: false,
    ttp: 15,
  },

  //SOUPS
  {
    item_name: "LEMON CORIANDER SOUP VEG",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "LEMON CORIANDER CHICKEN SOUP",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TOMATO SOUP",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SWEET CORN SOUP VEG",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SWEET CORN SOUP CHICKEN",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "Hot & Sour Soup Chicken",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: " Hot & Sour Soup VEG",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "Manchow Soup VEG",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "Manchow Soup CHICKEN",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: " Talimin Soup Chicken",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: " Talimin Soup VEG",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: " Wonton Soup VEG",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: " Wonton Soup Chicken",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG Yanchow Soup",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "Cream Of Mushroom",
    category: "Soup",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  // Continental Sizzler
  {
    item_name: "VEG CONTINENTAL SIZZLER",
    category: "Continental Sizzler",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG MEXICAN SIZZLER",
    category: "Continental Sizzler",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MEXICAN SIZZLER RICE",
    category: "Continental Sizzler",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "ITALIAN PASTA SIZZLER",
    category: "Continental Sizzler",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "COTTAGE CHEESE STEAK",
    category: "Continental Sizzler",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "GRILLED COTTAGE CHEESE",
    category: "Continental Sizzler",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "GRILLED FISH",
    category: "Continental Sizzler",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "GRILLED CHICKEN",
    category: "Continental Sizzler",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG SIZZLER SCHEZWAN SAUCE",
    category: "Continental Sizzler",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  // Continental Starter
  {
    item_name: "GRILLED VEGETABLES",
    category: "Continental Starter",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG LASAGNA",
    category: "Continental Starter",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PERI PERI PANEER",
    category: "Continental Starter",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SPINACH CHEESE BALLS",
    category: "Continental Starter",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CORN SPINACH CHEESE ROLL",
    category: "Continental Starter",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PERI PERI PANEER CHEESE BITES",
    category: "Continental Starter",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUSHROOM DUPLEX",
    category: "Continental Starter",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG NUGGETS",
    category: "Continental Starter",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CRISPY CHICKEN KEEMA CUTLET",
    category: "Continental Starter",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN NUGGETS",
    category: "Continental Starter",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  // WRAP
  {
    item_name: "VEG QUESADILLA",
    category: "Wrap",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER TIKKA WRAP",
    category: "Wrap",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI PANEER WRAP",
    category: "Wrap",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN TIKKA WRAP",
    category: "Wrap",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HARA BHARA KABAB WRAP",
    category: "Wrap",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  // Kathi roll
  {
    item_name: "PANEER TIKKA KATHI ROLL",
    category: "Kathi Roll",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG KATHI ROLL",
    category: "Kathi Roll",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN TIKKA KATHI ROLL",
    category: "Kathi Roll",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "EGG KATHI ROLL",
    category: "Kathi Roll",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PIZZA MARGARITA",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PIZZA MEXICANA",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER TIKKA PIZZA",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG COTTAGE CHEESE PERI PERI PIZZA",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "ROYAL PIZZA",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "DELUXE PIZZA",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "ORIENTAL EXPRESS PIZZA",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN TIKKA PIZZA",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "WOW PIZZA CHICKEN",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "GREEK KABAB PIZZA",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CARBONARA PIZZA",
    category: "Pizza",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PENNE ARABIATA VEG",
    category: "Pasta",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PENNE ARABIATA CHICKEN",
    category: "Pasta",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PENNE ALFREDO VEG",
    category: "Pasta",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PENNE ALFREDO CHICKEN",
    category: "Pasta",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PENNE IN PINK SAUCE VEG",
    category: "Pasta",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PENNE IN PINK SAUCE CHICKEN",
    category: "Pasta",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI NAZAKAT ALOO",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SHABNAM KE MOTI",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BHATTI PANEER TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI ROASTED SOYA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG SHEEK KABAB",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER MALAI TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HARYALI PANEER TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SOYA MALAI TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER TIKKA ACHARI",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CORN SHEEK KABAB",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER KALI MIRCH TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "LASOONI PANEER TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HARA BHARA KABAB",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "DAHI KE KABAB",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUSHROOM GALOUTI KABAB",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHANA DAL KE KABAB",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER HARI MIRCH KA ROLL",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SHIKAMPURI KABAB",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PERI PERI PANEER TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MULTANI PANEER TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI GOBHI",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CRISPY CHEESE PANEER TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHEESE CORN SPINACH SHEEK",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER SHEEK KABAB",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PALAK CHOLE TIKKI",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG BURASI KABAB",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI CHAT",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SMOKY VEG PLATTER",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUSHROOM TIKKA",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER TIKKA SIZZLER",
    category: "Smokey Tandoori Starter Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI CHICKEN HALF",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI CHICKEN FULL",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "AFGANI ROASTED CHICKEN HALF",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "AFGANI ROASTED CHICKEN FULL",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MURGH MALAI TIKKA",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FISH TIKKA",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN SHEEK KABAB",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN TIKKA",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUTTON SHEEK KABAB",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN PAHADI TIKKA",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BHATTI MURGH TIKKA",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN LASOONI TIKKA",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN LAZEEZ TIKKA",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN ACHARI TIKKA",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN HARYALI TIKKA",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN SHAMI KABAB",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUTTON GALOUTI KABAB",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN ROZALI KABAB",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN SHIKANDARI KABAB",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MURGH BANJARA KABAB",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "GILLAFI SEEK KABAB",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "LAHORI CHICKEN TIKKA",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MURGH SULTANA KABAB",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KALMI KABAB",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "EGG SCOTCH",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SMOKY NON VEG PLATTER",
    category: "Smokey Tandoori Roasted Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FISH AJWAIN TIKKA",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FISH PAHADI TIKKA",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FISH KALI MIRCH TIKKA",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FISH FINGER",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FISH N. CHIPS",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI FISH",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "LEMON FISH",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FISH BLACK PEPPER SAUCE",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI PRAWNS",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI MALAI PRAWNS",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI PRAWNS",
    category: "Fish / Prawns",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HONEY CHILLI POTATO",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG MANCHURIAN (GRAVY)",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG MANCHURIAN (DRY)",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER MANCHURIAN (GRAVY)",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER MANCHURIAN (DRY)",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KASHMIRI DUM ALOO",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG NOODLES",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "GOLDEN FRY BABY CORN",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI BABY CORN",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CORN SALT N PEPPER",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI PANEER (DRY)",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI PANEER (GRAVY)",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER KUNG PAO (DRY / GRAVY)",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHEESE CIGAR ROLL",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG SPRING ROLL",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUSHROOM CHILLI DRY",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUSHROOM CHILLI GRAVY",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI SOYA CHAAP (DRY / GRAVY)",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG GREEN THAI CURRY ( WITH RICE)",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI GARLIC TOFU",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG LOLIPOP",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG 99",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER SHANGHAI",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "DRAGON PANEER",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG TEMPURA",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER NOODLES",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHEESE CORN ROLL",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEGETABLE CHILLI STICK",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CRISPY ROLL",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "LUDHIANVI CHILLI PANEER",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHINA TOWN SIZZLER",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHINESE SIZZLER",
    category: "Chinese Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN MANCHURIAN (DRY)",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN MANCHURIAN (GRAVY)",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CRISPY HONEY CHICKEN",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN NOODLES",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN IN HOT GARLIC SAUCE",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN 65 (DRY / GRAVY)",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI CHICKEN (GRAVY)",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI CHICKEN (DRY)",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN LOLIPOP",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN RED THAI CURRY (WITH RICE)",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HUNAN CHICKEN DRY",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SICHUAN CHICKEN DRY",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN KUNG PAO",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "DRAGON CHICKEN DRY",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN MAJESTIC ANDRA STYLE",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN BLACK BEAN SAUCE",
    category: "Chinese Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG CHOPSUEY",
    category: "Chopsuey",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN AMERICAN CHOPSUEY",
    category: "Chopsuey",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HEALTHY GREEN SALAD",
    category: "Salad",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "GREEK SALAD",
    category: "Salad",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SOM TAM SALAD",
    category: "Salad",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CEASER SALAD",
    category: "Salad",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "RUSSIAN SALAD",
    category: "Salad",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG GRILLED SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER GRILLED SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG CHEESE SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG CLUB SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEGETABLE CORN CHEESE SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHEESE BURSTA PIZZA SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHEESE BLAST GRILLED SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BOMBAY SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN GRILLED SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN CLUB SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "EGG GRILLED SANDWICH",
    category: "Sandwich",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "YELLOW DAL TADKA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "DAL MAKHANI",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PUNJABI DAL TADKA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "AWADHI MALAI KOFTA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KHUMB HUSAINY",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KHUMB DO PYAZA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SOYA TIKKA MASALA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "METHI MATAR MALAI",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER LABABDAR",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER DO PYAZA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KHUMB MATAR MASALA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HANDI PANEER",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KADHAI PANEER",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MIX VEGETABLE",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PUNJABI DUM ALOO",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER TIKKA MASALA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER KALI MIRCH MASALA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "JEERA ALOO",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "ALOO GOBHI ADRAKI",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PALAK PANEER",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER KOLAPURI",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER BUTTER MASALA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER BHURJI",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KAJU CURRY",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG MAHARAJA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER PASANDA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BAWLI HANDI",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "LAHORI PANEER",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG JAIPURI",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG KEEMA MASALA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER PATIALA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BHINDI MASALA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PALAK CORN MASALA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG KOFTA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER HYDERABADI",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER ANGARA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER KHURCHAN",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER NARGISI KOFTA",
    category: "Indian Main Course Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "DHABA STYLE CHICKEN CURRY",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN KALI MIRCH MASALA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MALAI KOFTA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BUTTER CHICKEN HALF",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BUTTER CHICKEN FULL",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "EGG CURRY",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN LABABDAR",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN RARA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KADHAI CHICKEN",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN TIKKA MASALA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PATIALA CHICKEN",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MURGH MASALA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN DO PYAZA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN CORN MASALA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HANDI CHICKEN",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "DHABA CHICKEN",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANGDI MASALA (4 PCS)",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN BHUNA MASALA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PAHADI CHICKEN",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KASHMIRI CHICKEN MASALA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUTTON DO PYAZA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HANDI MUTTON",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PAHADI MUTTON",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUTTON RARA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "ROGAN JOSH KHAS",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "RAJASTHANI LAL MASH",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FISH MASALA",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FISH CURRY",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PRAWN CURRY",
    category: "Indian Main Course Non Veg",
    qty: 1,
    nc: false,
    ttp: 15,
  },

  //JAPANESE FOOD
  {
    item_name: "California Sushi",
    category: "Japanese",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "Vegan Sushi",
    category: "Japanese",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "Japanese Pan Thai Noodles",
    category: "Japanese",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  //JAPANESE FOOD
  {
    item_name: "STEAM RICE",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "EGG BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MUTTON BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "JEERA RICE",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PEACE PULAO",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG PULAO",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG AWADHI BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG SMOKEY HYDERABADI BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG HYDERABADI BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN HYDERABADI BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MALABAR CHICKEN BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "AUTHENTIC HYDERABADI MATKA BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "AWADHI KABAB DUM BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MURGH TYALANI BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PRAWN BIRYANI",
    category: "Rice / Biryani",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG FRIED RICE",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG SCHEZWAN FRIED RICE",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SPINACH CHILLI GARLIC RICE",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VEG TRIPLE FRIED RICE",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN FRIED RICE",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN TRIPLE FRIED RICE",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN SCHEZWAN FRIED RICE",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "EGG FRIED RICE",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI GARLIC NOODLES VEG",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI GARLIC NOODLES PANEER",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI GARLIC NOODLES CHICKEN",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI GARLIC NOODLES EGG",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HAKKA NOODLES VEG",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HAKKA NOODLES PANEER",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "HAKKA NOODLES CHICKEN",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SCHEWAN NOODLES VEG",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SCHEWAN NOODLES CHICKEN",
    category: "Fried Rice / Noodles",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MIX RAITA",
    category: "Raita",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PINEAPPLE RAITA",
    category: "Raita",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BOONDI RAITA",
    category: "Raita",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CUCUMBER RAITA",
    category: "Raita",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PAHADI RAITA",
    category: "Raita",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MIX FRUIT RAITA",
    category: "Raita",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "IDLY",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MASALA IDLY",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "VADA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PLAIN DOSA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "ONION DOSA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER DOSA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MIX MASALA DOSA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MASALA DOSA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHEESE MASALA DOSA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "RAVA DOSA PLAIN",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "RAVA MASALA DOSA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MYSORE MASALA DOSA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FAMILY MASALA DOSA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "UTTAPAM MASALA",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "UTTAPAM ONION",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "UTTAPAM MIX VEGETABLE",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PLAIN UTTAPAM",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "RAVA UTTAPAM",
    category: "South Indian",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TANDOORI ROTI",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BUTTER ROTI",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MISSI ROTI",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "LACHHA PARATHA",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHILLI PARATHA (RED/ GREEN)",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PLAIN NAAN",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "GARLIC NAAN",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BUTTER NAAN",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "STUFFED NAAN",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHEESE STUFFED NAAN",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "AMRITSARI KULCHA",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "ONION KULCHA",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PANEER KULCHA",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KHASTA ROTI",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KASHMIRI NAAN",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PUDINA PARATHA",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MIX KULCHA",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHICKEN KEEMA NAAN",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BREADS BASKET",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "FAMILY NAAN",
    category: "Indian Breads",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SHAHI TUKRA",
    category: "Dessert",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SIZZLER BROWNIE WITH ICE CREAM",
    category: "Dessert",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "GULAB JAMUN (2 PCS)",
    category: "Dessert",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MOONG DAL HALWA",
    category: "Dessert",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "JALABI WITH RABRADI",
    category: "Dessert",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "RASMALAI (2 PCS)",
    category: "Dessert",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KULFI FALUDA",
    category: "Dessert",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CHOICE OF ICE CREAM",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TUTTI FURTITY",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "KESSER PISTA",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SINGLE SUNDAY",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "RAJBHOG ICE CREAM",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "COOKIES AND CREAM",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BANANA SPLIT",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "CUSTARD ICE CREAM",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "DOUBLE SUNDAY ICE CREAM",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "TRIPLE SUNDAY ICE CREAM",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "BLACK FOREST SUNDAY",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "SUPER SUNDAY ICE CREAM",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "PINEAPPLE BULK",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "ORIGINAL MOON BLACK",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "MELTED CARAMEL",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
  {
    item_name: "STRAWBERRY FLAVOUR",
    category: "Ice Cream",
    qty: 1,
    nc: false,
    ttp: 15,
  },
];

export default itemData;
